
name: Deploy via AWS SAM

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: SAM Validate
      run: |
        cat >samconfig.toml <<'EOF'
        ${{ vars.SAMCONFIG_TOML }}
        EOF
        sam --version
        sam validate
        pip install -r src/newsletter_email/requirements.txt -t src/newsletter_email/dependencies/python

    - name: SAM Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        sam deploy
